#Server Port
server:
  port: 8080

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
#  datasource:
#    url: jdbc:h2:file:./basic_social_media
    url: jdbc:h2:mem:testdb
    username: root
    password:
    driverClassName: org.h2.Driver
